### ISSUE TITLE
Transparency Issue when converting glTF to usdz #88

### ISSUE THREAD

**Issue by ShantanuSriv** [kcoley/gltf2usd#95] opened 2018-11-05 10:32 UTC
Reopening as transparency issue is still not handled. #88

**Comment by kcoley** [comment] 2018-11-05 13:54
Hi @ShantanuSriv do you have a sample glTF model I can use for reference?

**Comment by ShantanuSriv** [comment] 2018-11-06 05:33
@kcoley  No, I can't share the glTF model because it's a private proprietary. I can share the screenshots only. 

Please tell me if I can help you in any way possible.

**Comment by kcoley** [comment] 2018-11-06 05:40
@ShantanuSriv no worries, I have a few questions then:

1. In the glTF files, are any of the base color textures shared across multiple materials which have different blend modes?  For example, one material uses opaque, while the other uses alpha blend, but the exact same base color texture?

2. Are the glTF models using specular glossiness or metallic roughness?

3.  Do the glTF models use alpha in the vertex colors?

4.  Are any of the glTF models using alpha mask?

If any questions need more detail, please let me know

**Comment by ShantanuSriv** [comment] 2018-11-06 06:15
> In the glTF files, are any of the base color textures shared across multiple materials which have different blend modes? For example, one material uses opaque, while the other uses alpha blend, but the exact same base color texture?

Yes, we have this case in some of the glTF files

> Are the glTF models using specular glossiness or metallic roughness?

Metallic roughness

> Do the glTF models use alpha in the vertex colors?

No

> Are any of the glTF models using alpha mask?

 No

**Some of the answers may vary on the size of the sample of glTF models. But as of now, in my sample set, I have these verified.**

**Comment by kcoley** [comment] 2018-11-06 06:17
@ShantanuSriv gotcha.  I'm guessing case 1 may be a possible issue here.  I can make a change to duplicate the texture without alpha if it is shared across two different materials with different blend modes to see if that helps.

**Comment by kcoley** [comment] 2018-11-07 06:42
@ShantanuSriv I pushed another update to master: https://github.com/kcoley/gltf2usd/pull/96

Does this help or is the problem still persisting?

**Comment by kcoley** [comment] 2018-11-09 06:35
@ShantanuSriv closing for now, but feel free to reopen if the issue is still coming up

**Closed by kcoley** 2018-11-09 06:35 UTC
