### ISSUE TITLE
Latest converter update is confusing and has weird issues...

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#63] opened 2018-09-29 02:57 UTC
I'm wondering what's the best way to install the Python module. In the past, I simply copy paste all the files in the source into the folder where the gltf asset is, and then run the Python tool:

<img width="215" alt="screen shot 2018-09-29 at 09 55 47" src="https://user-images.githubusercontent.com/3952687/46240189-e9060d00-c3cd-11e8-8fa8-6886175d4bec.png">

But in the latest update the tools have grown and when I tested a conversion using the tests asset, I keep getting weird error:
```
TATATs-MacBook-Pro:Start_Walking jimmyg$ python gltf2usd.py -g Start_Walking.gltf -o Start_Walking.usdz
converted usd file extension from .usdz to .usdc: Start_Walking.usdc
Traceback (most recent call last):
  File "gltf2usd.py", line 726, in <module>
    convert_to_usd(args.gltf_file, args.usd_file, args.fps, args.scale, args.arkit, args.verbose, args.use_euler_rotation)
  File "gltf2usd.py", line 679, in convert_to_usd
    usd = GLTF2USD(gltf_file=gltf_file, usd_file=usd_file, fps=fps, scale=scale, verbose=verbose, use_euler_rotation=use_euler_rotation)
  File "gltf2usd.py", line 68, in __init__
    self.convert()
  File "gltf2usd.py", line 655, in convert
    self._convert_images_to_usd()
  File "gltf2usd.py", line 414, in _convert_images_to_usd
    shutil.copyfile(image_path, image_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `Boss_diffuse.png` and `/Users/jimmyg/Documents/PROJECT20180922/Madain_Saleh/anim3/tests/assets/Start_Walking/Boss_diffuse.png` are the same file

```

UPDATE: Regarding me being dumb copy pasting the script into the folder, I just realized I can keep the original Tool, then open terminal inside the source tool folder and then **drag and drop the GLTF file** to be converted and then simply just output the result inside any folder. I am still getting familiar with commands and terminal.

For example:
<img width="774" alt="screen shot 2018-09-29 at 14 17 45" src="https://user-images.githubusercontent.com/3952687/46242370-76f3ef00-c3f2-11e8-96d5-b27529505869.png">

**Comment by enzyme69** [comment] 2018-09-29 03:08
Another example I am testing is this Two Tentacles animation.

<img width="1119" alt="screen shot 2018-09-29 at 10 04 02" src="https://user-images.githubusercontent.com/3952687/46240296-7138e200-c3cf-11e8-8914-02d7919732ed.png">

[ori.zip](https://github.com/kcoley/gltf2usd/files/2430234/ori.zip)

Originally I have 2 separate armatures for each tentacle. It does not export correctly from Blender to GLTF. So I ensure armature are joined into a single armature with many branches.

GLTF works correctly at GLTF online viewer.

When I am converting the result is this weirdness:
<img width="630" alt="screen shot 2018-09-29 at 10 08 36" src="https://user-images.githubusercontent.com/3952687/46240305-a6453480-c3cf-11e8-85c2-e3c46145f3f3.png">

**Comment by kcoley** [comment] 2018-09-29 17:09
Hi @enzyme69 do you have the original .blend file for the ori model?

**Comment by kcoley** [comment] 2018-10-01 04:32
@enzyme69 actually, I was able to create a similar model in Maya and can now reproduce the issue.  I think I know what is happening now and am working on a fix.  Thanks again for the reference model!

**Comment by enzyme69** [comment] 2018-10-01 04:35
@kcoley Glad it is useful :) Your tools become defacto GLTF to USDZ conversion!
[two_tentacles_002.blend.zip](https://github.com/kcoley/gltf2usd/files/2432582/two_tentacles_002.blend.zip)

**Comment by kcoley** [comment] 2018-10-06 21:58
Hi @enzyme69 .  This took a while for me to get my copy of the Maya USD exporter to work, but now I know what I have to fix in the exporter to support multiple meshes sharing the same skeleton.  Unfortunately, it looks like multiple skeletons currently do not animate on iOS or Mac OS, as alluded to by @wave-electron in this issue: https://github.com/kcoley/gltf2usd/issues/49

The only way to view the model would be through usdview, the Maya, or Houdini USD importers.  @wave-electron mentioned a workaround by combining the meshes into one and sharing the same uv map to get it to work on iOS on that issue.  

Here is a version of your model with two meshes in usdz (converted to fbx, imported to maya and exported as usd): 
[two_tentacles_002.usdz.zip](https://github.com/kcoley/gltf2usd/files/2453455/two_tentacles_002.usdz.zip)

Hopefully an upcoming iOS/Mac OS update will get this file to work.

**Comment by kcoley** [comment] 2018-10-15 17:06
@enzyme69 I did some reorganization of the project in the lastest merge, so now you just need `gltf2usd.py`, `__init__.py`, and the `_usdz` folder.  Hopefully that makes things easier to move around.

**Comment by kcoley** [comment] 2018-12-12 07:47
Closing this for now

**Closed by kcoley** 2018-12-12 07:47 UTC
